# Generated by Django 5.2.4 on 2025-07-31 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Názov náradia')),
                ('tool_type', models.CharField(max_length=100, verbose_name='Typ')),
                ('category', models.CharField(max_length=100, verbose_name='Kategória')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Sériové číslo')),
                ('purchase_date', models.DateField(verbose_name='Dátum zakúpenia')),
                ('warranty_until', models.DateField(verbose_name='Platnosť záruky')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Dátum výdaja')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Dátum príjmu na sklad')),
                ('status', models.CharField(choices=[('sklad', 'Na sklade'), ('vydane', 'Vydané'), ('poskodene', 'Poškodené'), ('cakajuci_servis', 'Čaká sa na opravu'), ('v_servise', 'V oprave'), ('vyradene', 'Vyradené'), ('stratene', 'Stratené')], default='sklad', max_length=20, verbose_name='Stav')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.branch', verbose_name='Pobočka')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Dátum servisu')),
                ('description', models.TextField(verbose_name='Popis opravy alebo úkonu')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tools.tool')),
            ],
        ),
        migrations.CreateModel(
            name='ToolHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=100)),
                ('change_description', models.TextField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
        ),
    ]
